### ISSUE TITLE
制作了一个可能更快一些的捷径

### ISSUE THREAD

**Issue by mgdreamingstar** [MiracleXYZ/ZotExpert#2]
第二个 JSBox 的调用经常会卡住，捷径本身也可以发起 Get 请求，所以把第二部分换成了捷径自己的动作，好想会快一些。下面是改后的捷径：
https://www.icloud.com/shortcuts/b81f4165d3514d248d5b9d81179ab2c5

**Comment by MiracleXYZ** [comment]
由于是第一次用快捷指令，我并不知道可以发起 GET 请求以及做文本匹配；看起来这项工作只需要快捷指令就可以完成了~

根据你发的快捷指令，我估计你使用的是「绝对路径」储存附件，这样仍然会储存具有操作系统特征的路径（如Windows的反斜线）；如果改成用「相对路径」的话，附件会统一命名为 `attachments:` 开头的路径，代码还可以再简单一些……

**Comment by mgdreamingstar** [comment]
嗯，刚刚看了下发现是 zotero 的设置，现在改过来了。谢谢提醒。
