### ISSUE TITLE
我最后能打开PDF Export，但是打不开指定的文件。请问下，我是哪里有问题？谢谢！

### ISSUE THREAD

**Issue by sprswa** [MiracleXYZ/ZotExpert#4]
PDF Export原先是什么界面，打开后还是那个界面。就是不能打开指定的文件。

**Comment by MiracleXYZ** [comment]
一般这种情况有两个原因：
1. 文件在下载中。这种情况再打开一次就可以了。
2. 配置有误。请检查：
  a. ZotFile是否配置为**相对路径**：如果在设置之前Zotero中已经有相应的文献，那么需要重命名一遍，具体方法是全选所有的条目，右键，然后Rename
  b. 同步文件夹名称是否填写正确

**Comment by MiracleXYZ** [comment]
如果还不能打开，你可以暂时切换回Zotero网页版的旧版Library，点开附件的 Attachment Details，查看最下面一行（也就是路径）写的是什么：如果正确配置，应该显示为 `attachments:xxx/yyy.pdf` 的形式。

**Comment by sprswa** [comment]
感谢您的回复，attachments details应该是对的。
[Image.jpeg]
运行捷径后文件能找到，自动打开了 PDF Expert后还是打不开制定文件。


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Yuzhang Xie <notifications@github.com>
发送时间: Tuesday, February 11, 2020 3:20:09 PM
收件人: MiracleXYZ/ZotExpert <ZotExpert@noreply.github.com>
抄送: sprswa <sprswa@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [MiracleXYZ/ZotExpert] 我最后能打开PDF Export，但是打不开指定的文件。请问下，我是哪里有问题？谢谢！ (#4)


如果还不能打开，你可以暂时切换回Zotero网页版的旧版Library，点开附件的 Attachment Details，查看最下面一行（也就是路径）写的是什么：如果正确配置，应该显示为 attachments:xxx/yyy.pdf 的形式。

―

**Comment by sprswa** [comment]
下面是我相关设置的截图，您能帮我看下有什么问题吗？
![](https://raw.githubusercontent.com/sprswa/PicGo/master/img/20200211153439.JPG)
![](https://raw.githubusercontent.com/sprswa/PicGo/master/img/20200211153417.JPG)
![](https://raw.githubusercontent.com/sprswa/PicGo/master/img/20200211153305.png)
![](https://raw.githubusercontent.com/sprswa/PicGo/master/img/20191231171403.png)

我在捷径中填的文件夹名是storage。

**Comment by MiracleXYZ** [comment]
【注意】
应该把 Zotero 设置中的文件夹**直接同步**到 PDF Expert 中，文件夹名也是直接填写，不要使用任何子文件夹。
